# Generated by Django 3.1.1 on 2020-09-30 07:39

import Object_recog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Object_recog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=Object_recog.models.vi_path_and_rename)),
            ],
        ),
    ]
