# Generated by Django 2.2.2 on 2020-10-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pincode',
            field=models.CharField(default=111, max_length=15),
            preserve_default=False,
        ),
    ]
