# Generated by Django 2.2.2 on 2020-10-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='adhaar_card',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='econtact',
            field=models.CharField(max_length=10),
        ),
    ]
