# Generated by Django 3.1.1 on 2020-09-22 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imagefile', '0002_auto_20200921_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataup',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
