# Generated by Django 3.1.1 on 2020-09-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagefile', '0003_dataup_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataup',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='dataup',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='dataup',
            name='time',
        ),
        migrations.AlterField(
            model_name='dataup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
