# Generated by Django 3.1.1 on 2020-09-29 11:04

from django.db import migrations, models
import imagefile.models


class Migration(migrations.Migration):

    dependencies = [
        ('imagefile', '0006_auto_20200929_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=imagefile.models.vipath_and_rename)),
            ],
        ),
        migrations.AlterField(
            model_name='dataup',
            name='image',
            field=models.ImageField(upload_to=imagefile.models.impath_and_rename),
        ),
    ]
