# Generated by Django 2.2.2 on 2020-10-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagefile', '0008_video_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_train',
            name='video',
            field=models.FileField(upload_to='train'),
        ),
    ]
